export const Endpoints = {
    GET_PRODUCTS: 'products',
    NEWSLETTER: 'newsletter_subscription',
    REGISTER: 'signup',
    LOGIN: 'login',
    PROFILE: 'profile',
    UPDATE_PROFILE: 'details',
    CHANGE_PASSWORD: 'changePassword',
    WISHLIST: 'wishlist',
    PRODUCT: 'product',
    POST_REVIEW: 'review',
    COLOR_LIST: 'colors_list',
    SEND_OTP: 'forgotPassword',
    RESET_PASSWORD: 'resetPassword',
    SEND_MESSAGE: 'query',
    HOME_PRODUCTS: 'home_products',
    VALIDATE_PIN: 'check_pincode',
};
