export const Endpoints = {
    GET_PRODUCTS: 'products',
    NEWSLETTER: 'newsletter_subscription',
    SEND_LOGIN_OTP: 'sendLoginOtp',
    PROFILE: 'profile',
    UPDATE_PROFILE: 'details',
    CHANGE_PASSWORD: 'changePassword',
    WISHLIST: 'wishlist',
    PRODUCT: 'product',
    POST_REVIEW: 'review',
    COLOR_LIST: 'colors_list',
    SEND_OTP: 'forgotPassword',
    RESET_PASSWORD: 'resetPassword',
    SEND_MESSAGE: 'query',
    HOME_PRODUCTS: 'home_products',
    VALIDATE_PIN: 'check_pincode',
    CATEGORIES: 'product_categories',
    FEATURED_PRODUCT: 'featured_products',
    CREATE_ORDER: 'create_order',
    VERIFY_PAYMENT: 'payment',
    ORDERS: 'orders',
    ORDER: 'order',
    SEND_MOBILE_OTP: 'sendOtp',
    VERIFY_OTP: 'verifyLoginOtp',
    VERIFY_AUTH_OTP: 'verifyOtp',
};
