export const Keys = {
    GET_PRODUCTS: 'get-products',
    SUBSCRIBE: 'subscribe',
    REGISTER: 'register',
    LOGIN: 'login',
    PROFILE: 'profile',
    UPDATE_PROFILE: 'update-profile',
    CHANGE_PASSWORD: 'change-password',
    WISHLIST: 'wishlist',
    PRODUCT_DETAILS: 'product-details',
    POST_REVIEW: 'post-review',
    ALL_PRODUCTS: 'all-products',
    GET_COLORS: 'get-colors',
    GET_FILTERED_PRODUCTS: 'get-filtered-products',
    TOGGLE_WISHLIST: 'toggle-wishlist',
};
