export const Screens = {
    HOME: '/',
    CART: '/cart',
    CHECKOUT: '/checkout',
    WISHLIST: '/wishlist',
    LOGIN: '/login',
    PROFILE: '/profile',
    DUMMY_NOT_FOUND: '/notfound',
    PRODUCT_DETAILS: '/product',
    SHOP: '/shop',
    FORGOT: '/forgot',
    CONTACT: '/contact',
    FAQ: '/faq',
    ORDER_DETAILS: '/order',
    ORDER_TRACK: '/track',
    NOT_FOUND: '/*',
};
